config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  	get "search", to: "users#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tags_result' => 'tags#result'
  get '/search', to: 'searches#search'
  
  resources :groups, only:  [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  
  resources :chats, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments
  has_many :favorites
  
  has_many :view_counts, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :body, presence: true # 指定カラム「comment」が存在しないので変更
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image
  
  def is_owned_by?(user)
    owner.id == user.id
  end
  
  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User" # 構文ミス
  belongs_to :followed, class_name: "User" # 構文ミス
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :view_counts, dependent: :destroy
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower #throughの記述漏れ
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed #throughの記述漏れ

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy #followed_idで検索するためfind_byへ変更
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(weight, height)
    unless self.profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    self.profile_image.variant(resize_to_fill: [weight,height]).processed
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    @book_comment = BookComment.new
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = book.id
    @comment.save
    # redirect_to book_path(book.id)
    # 非同期のため削除
  end

  def destroy
    # book = Book.find(params[:book_id]) # showページ遷移用変数
    @book_comment = BookComment.new
    @comment = BookComment.find(params[:id]) #findでPKを検索
    @comment.destroy
    # redirect_to book_path(book.id)
    # 非同期のため削除
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_counter.html.erb
コメント数: <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, book_comment], local: false) do |f| %>
  <%= f.text_area :body, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信する", class: "btn btn-lg btn-success" %>
<% end %>
<!--local: falseへ変更-->

app/views/book_comments/_index.html.erb
<table>
  <tbody>
      <% book.book_comments.each do |book_comment| %>
      <tr>
        
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= image_tag book_comment.user.get_profile_image(80,80) %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.body %></td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-danger pull-right", remote: true %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/book_comments/create.js.erb
$('.comment-textarea').val("");
$('.book-comments-counter').html("<%= j(render 'book_comments/counter', book: @comment.book) %>");
<!--)を追加-->
$('.book-comments-index').html("<%= j(render 'book_comments/index', book: @comment.book) %>");
$('.book-comments-form').html("<%= j(render 'book_comments/form', book: @comment.book, book_comment: @book_comment) %>");

app/views/book_comments/destroy.js.erb
$('.book-comments-counter').html("<%= j(render 'book_comments/counter', book: @comment.book) %>");
<!--)を追加-->
$('.book-comments-index').html("<%= j(render 'book_comments/index', book: @comment.book) %>");
$('.book-comments-form').html("<%= j(render 'book_comments/form', book: @comment.book, book_comment: @book_comment) %>");