config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  	get "search", to: "users#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tags_result' => 'tags#result'
  get '/search', to: 'searches#search'
  
  resources :groups, only:  [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  
  resources :chats, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments
  has_many :favorites
  
  has_many :view_counts, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :body, presence: true # 指定カラム「comment」が存在しないので変更
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image
  
  def is_owned_by?(user)
    owner.id == user.id
  end
  
  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User" # 構文ミス
  belongs_to :followed, class_name: "User" # 構文ミス
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :view_counts, dependent: :destroy
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy
  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower #throughの記述漏れ
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed #throughの記述漏れ

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy #followed_idで検索するためfind_byへ変更
  end

  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(weight, height)
    unless self.profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    self.profile_image.variant(resize_to_fill: [weight,height]).processed
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def result
           tag = params[:tag]
           @search_books = Book.where(tag: "#{tag}")
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @books_today = @books.where(created_at: Time.zone.now.all_day)
    @books_2days_ago = @books.where(created_at: 2.day.ago.all_day)
    @books_3days_ago = @books.where(created_at: 3.day.ago.all_day)
    @books_4days_ago = @books.where(created_at: 4.day.ago.all_day)
    @books_5days_ago = @books.where(created_at: 5.day.ago.all_day)
    @books_6days_ago = @books.where(created_at: 6.day.ago.all_day)
    @books_yesterday = @books.where(created_at: 1.day.ago.all_day)
    @books_this_week = @books.where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day)
    @books_last_week = @books.where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day)
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books 
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(80,80) %></td>
        <td><%= user.name %></td>
        <td><%= render "relationships/btn", user: user %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <td><%= user.name %></td>
  </tr>
  <tr>
	  <th>introduction</th>
	  <td><%= user.introduction %></td>
  </tr>
  <tr>
    <th>follows</th>
    <td><%= link_to user.followings.count, user_followings_path(user) %></td>
  </tr>
  <tr>
    <th>followers</th>
    <td><%= link_to user.followers.count, user_followers_path(user) %></td>
  </tr>
</table>
　
<div class='row mb-3'>
  <% if current_user != user %>
    <%= render "relationships/btn", user: user %>
  <% end %>
  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
  <%= link_to 'chatを始める', chat_path(user.id), class: "btn btn-link ml-3" %>
  <% end %>
</div>
<div class="row">
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%=link_to "グループを作成する",new_group_path %> | 
      <%=link_to "グループ一覧",groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('.search_result').html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <div class="mb-5">
        <h3>投稿数の前日比・前週比</h3>
        <div class="table_width">
          <table class="table table-bordered">
            <thead>
            <tr>
              <th>今日の投稿</th>
              <th>昨日の投稿</th>
              <th>前日比</th>
            </tr>
            </thead>
            <tbody>
              <tr>
      	  <td><%= @books_today.count %></td>
      	  <td><%= @books_yesterday.count %></td>
              <% if @books_yesterday.count == 0 %>
      	  <td>前日の投稿はなし</td>
              <% else %>
      	  <td><% @books_the_day_before =   @books_today.count / @books_yesterday.count  %>
      	  <%= (@the_day_before * 100).round %>%</td>
              <% end %>
              </tr>
            </tbody>
          </table>
            
          <table class="table table-bordered">
            <thead>
            <tr>
              <th>今週の投稿</th>
              <th>先週の投稿</th>
              <th>先週比</th>
            </tr>
            </thead>
            <tbody>
              <tr>
      	  <td><%= @books_this_week.count %></td>
      	  <td><%= @books_last_week.count %></td>
              <% if @books_last_week.count == 0 %>
      	  <td>先週の投稿はなし</td>
              <% else %>
      	  <td><% @the_week_before = @books_this_week.count / @books_last_week.count  %>
      	  <%= (@the_week_before * 100).round %>%</td>
              <% end %>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      
      <div class="mb-5">
        <h4>7日間分の投稿数</h4>
          <table class='table table-bordered'>
            <thead>
              <tr> 
                <th>６日前</th>
                <th>５日前</th>
                <th>４日前</th>
                <th>３日前</th>
                <th>２日前</th>
                <th>１日前</th>
                <th>今日</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @books_6days_ago.count %></td>
                <td><%= @books_5days_ago.count %></td>
                <td><%= @books_4days_ago.count %></td>
                <td><%= @books_3days_ago.count %></td>
                <td><%= @books_2days_ago.count %></td>
                <td><%= @books_yesterday.count %></td>
                <td><%= @books_today.count %></td>
              </tr>
            </tbody>
          </table>
        
        <canvas id="myLineChart"></canvas>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
          <script>
            $(document).on('turbolinks:load', function() {
              var ctx = document.getElementById("myLineChart");
              var myLineChart = new Chart(ctx, {
                type: 'line',
                data: {
                  labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
                  datasets: [
                    {
                      label: '投稿した本の数',
                      data: [
                        <%= @books_6days_ago.count %>,
                        <%= @books_5days_ago.count %>, 
                        <%= @books_4days_ago.count %>, 
                        <%= @books_3days_ago.count %>, 
                        <%= @books_2days_ago.count %>, 
                        <%= @books_yesterday.count %>, 
                        <%= @books_today.count %>
                      ],
                      borderColor: "rgba(0,0,255,1)",
                      backgroundColor: "rgba(0,0,0,0)",
                      tension: 0.4
                    }
                  ],
                },
                options: {
                  title: {
                    display: true,
                    text: '7日間の投稿数の比較'
                  },
                  responsive: true,
                  scales: {
                    y:{
                      suggestedMin: 0,
                      suggestedMax: 10
                    },
                    x:{
                      stacked: true
                    },
                  },
                }
              });
            });
          </script>
      </div>
      <%= form_with url: user_search_path(@user), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: 'btn btn-primary'  %>
      <% end %>
      
      <div class="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
  </div>
</div>